In [4]:
#Q1
#The following is a list of 10 students ages:
# ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
# • Sort the list and find the min and max age
# • Add the min age and the max age again to the list
# • Find the median age (one middle item or two middle items divided by two)
# • Find the average age (sum of all items divided by their number)
# • Find the range of the ages (max minus min)

import statistics

ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
#sort()-for sorting
ages.sort()
print("Ages sorted: ", ages)
# min() - for min values in list
print("Min value of ages: ", min(ages))
# max() - for max values in list
print("Max value of ages: ", max(ages))
# append(values)- for inserting values
ages.append(min(ages))
ages.append(max(ages))
ages.sort()
print("Ages sorted: ", ages)
print("Median: ", statistics.median(ages))
print("Average: ", statistics.mean(ages))
print("Range: ", max(ages)-min(ages))

Ages sorted:  [19, 19, 20, 22, 24, 24, 24, 25, 25, 26]
Min value of ages:  19
Max value of ages:  26
Ages sorted:  [19, 19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 26]
Median:  24.0
Average:  22.75
Range:  7


In [8]:
#Q2
dog= dict()
#adding key value pairs
dog.update({"name":"One", "color":"Black", "breed":"Husky", "legs":4, "age":10})
print("dog dictionary: ",dog)

student_dict = dict()

#updating sample values
student_dict.update({"first_name": "Tasneem", "last_name": "Shaik", "gender": "Male", "age": "23",
                     "marital status": "Single", "skills": ["Python"], "country": "India", "city": "Vijayawada",
                     "address": "Sanathnagar 3rd line"})


print("\nStudent_dict ", student_dict)
#using len() for getting length
print("\nLength of Student_Dictionary: ", len(student_dict))

#Get the value of skills and check the data type, it should be a list
print("\nValues of skills: ",student_dict["skills"])
print("\nData Type of Skills: ", type(student_dict["skills"]))

#Modify the skills values by adding one or two skills
student_dict["skills"].extend(["ReactJS", "JavaScript"])
print("\nUpdated values: ", student_dict["skills"])

#Get the dictionary keys as a list
#Get the dictionary values as a list
print(student_dict.keys())
print(student_dict.values())

dog dictionary:  {'name': 'One', 'color': 'Black', 'breed': 'Husky', 'legs': 4, 'age': 10}

Student_dict  {'first_name': 'Tasneem', 'last_name': 'Shaik', 'gender': 'Male', 'age': '23', 'marital status': 'Single', 'skills': ['Python'], 'country': 'India', 'city': 'Vijayawada', 'address': 'Sanathnagar 3rd line'}

Length of Student_Dictionary:  9

Values of skills:  ['Python']

Data Type of Skills:  <class 'list'>

Updated values:  ['Python', 'ReactJS', 'JavaScript']
dict_keys(['first_name', 'last_name', 'gender', 'age', 'marital status', 'skills', 'country', 'city', 'address'])
dict_values(['Tasneem', 'Shaik', 'Male', '23', 'Single', ['Python', 'ReactJS', 'JavaScript'], 'India', 'Vijayawada', 'Sanathnagar 3rd line'])


In [9]:
#Q3
sisters = ("Karishma","Zoya")
print("Sisters: ", sisters,)
brothers = ("Chand","Saleem")
print("Brothers: ", brothers)
siblings = sisters+brothers
print("Siblings: ",siblings)
print("No of Siblings:", len(siblings))
family_members = siblings+("Apsar","Tajuddin")
print("family_members: ", family_members)


Sisters:  ('Karishma', 'Zoya')
Brothers:  ('Chand', 'Saleem')
Siblings:  ('Karishma', 'Zoya', 'Chand', 'Saleem')
No of Siblings: 4
family_members:  ('Karishma', 'Zoya', 'Chand', 'Saleem', 'Apsar', 'Tajuddin')


In [14]:
#Q4


it_companies = {'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'}
# Find the length of the set it_companies
print("Set length:",len(it_companies))
# • Add 'Twitter' to it_companies
it_companies.add('Twitter')
print("it_companies: ", it_companies)
# • Insert multiple IT companies at once to the set it_companies
it_companies.update(['Tcs','Deliotte','Google'])
print("it_companies after update: ",it_companies)
# • Remove one of the companies from the set it_companies
it_companies.remove("Deliotte")
print(it_companies)

# • What is the difference between remove and discard
print("\n The discard() method removes the specified item from the set. This method is different from the remove() method, because the remove() method will raise an error if the specified item does not exist, and the discard() method will not.")
A = {19, 22, 24, 20, 25, 26} 
B = {19, 22, 20, 25, 26, 24, 28, 27} 
# • Join A and B
print("\n A union B: ",A.union(B))
# • Find A intersection B
print("A  Intersection B: ",A.intersection(B))
# • Is A subset of B
print("A is Subset of B? ",A.issubset(B))
# • Are A and B disjoint sets
print("A and B are disjoint sets? ",A.isdisjoint(B))

# • Join A with B and B with A
print("AUB: ",(A.union(B)))
print("BUA: ",(B.union(A)))
      
# • What is the symmetric difference between A and B
print("Symmetric Difference of A with B: ",A.symmetric_difference(B))
      
# • Delete the sets completely
A.clear()
B.clear()
print("After clear Set A values: ", A,"\tSet B values: ",B)
      
# • Convert the ages to a set and compare the length of the list and the set.
age = [22, 19, 24, 25, 26, 24, 25, 24] 
age_set = set(age)
print("set of ageslist: ", age_set)
print("Length of age list: ", len(age), "\nLength of age set",len(age_set))
print("#list have duplicate values and set doesnt allow deuplicates")



Set length: 7
it_companies:  {'Apple', 'Amazon', 'Facebook', 'IBM', 'Microsoft', 'Twitter', 'Oracle', 'Google'}
it_companies after update:  {'Deliotte', 'IBM', 'Amazon', 'Tcs', 'Facebook', 'Twitter', 'Apple', 'Microsoft', 'Oracle', 'Google'}
{'IBM', 'Amazon', 'Tcs', 'Facebook', 'Twitter', 'Apple', 'Microsoft', 'Oracle', 'Google'}

 The discard() method removes the specified item from the set. This method is different from the remove() method, because the remove() method will raise an error if the specified item does not exist, and the discard() method will not.

 A union B:  {19, 20, 22, 24, 25, 26, 27, 28}
A  Intersection B:  {19, 20, 22, 24, 25, 26}
A is Subset of B?  True
A and B are disjoint sets?  False
AUB:  {19, 20, 22, 24, 25, 26, 27, 28}
BUA:  {19, 20, 22, 24, 25, 26, 27, 28}
Symmetric Difference of A with B:  {27, 28}
After clear Set A values:  set() 	Set B values:  set()
set of ageslist:  {19, 22, 24, 25, 26}
Length of age list:  8 
Length of age set 5
#list have duplicate v

In [15]:
#Q5

radius = 30
_area_of_circle_ = 3.14 * radius **2
print("Area :",_area_of_circle_)
_circum_of_circle_ = 2 * 3.14 * radius
print("Circumference of a circle = ",_circum_of_circle_)

_radius_of_circle_ = float(input("Enter radius of circle: "))
_area_of_circle_ = 3.14 * _radius_of_circle_ **2
print("Area of a circle = ",_area_of_circle_)



Area : 2826.0
Circumference of a circle =  188.4
Enter radius of circle: 10
Area of a circle =  314.0


In [16]:

#Q6
print("I am a teacher and I love to inspire and teach people")
words = ("I am a teacher and I love to inspire and teach people".split(" "))
set1=set(words)
print("Number of Unique words: ",len(set1), set1)



I am a teacher and I love to inspire and teach people
Number of Unique words:  10 {'a', 'am', 'inspire', 'teach', 'teacher', 'I', 'and', 'to', 'people', 'love'}


In [20]:
#Q7
sample = "Name \t Age \tCountry City"
sample2 ="\nAsabench 250 \tFinland Helsinki"
print(sample,sample2)


Name 	 Age 	Country City 
Asabench 250 	Finland Helsinki


In [21]:
#Q8
radius = 10 
area = 3.14 * radius ** 2 
#“The area of a circle with radius 10 is 314 meters square.”
print("The area of a circle with radius",radius,"is %.0f" %area, "meters square.")


The area of a circle with radius 10 is 314 meters square.


In [26]:
#Q9
students = int(input("Enter number of students: "))
wt_lb = list() 
wt_kg = list() 

for each in range(students):
    lb = int(input("Enter weight of {} student in lbs: ".format(each+1)))
    wt_lb.append(lb)
    kg = float("%.2f" %(lb*0.453592))
    wt_kg.append(kg)
    
print("weight of students in lbs: ",wt_lb)
print("weight of students in kgs: ",wt_kg)



Enter number of students: 1
Enter weight of 1 student in lbs: 1
weight of students in lbs:  [1]
weight of students in kgs:  [0.45]


In [5]:
#Q10
import numpy as nm   
import pandas as pd 
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import StandardScaler 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import confusion_matrix 

X= nm.array([[1,0],[2,0],[3,0],[6,0],[6,0],[7,0],[10,0],[11,0]])
print("Dataset: \n",X,"\n Size: ",len(X))
y = nm.array([0,0,1,1,1,0,0,0])
print("\nClass labels Y:",y)
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.50,random_state=0 ) 
print("\nTraining Data X: \n", x_train)
print("\nTraining Data label Y:", y_train)

stand_scalar= StandardScaler()    
x_train= stand_scalar.fit_transform(x_train)    
x_test= stand_scalar.transform(x_test) 

#Initialising KNN Classifier with value 3
classifier= KNeighborsClassifier(n_neighbors=3)  
#Fitting the data to classifier
classifier.fit(x_train, y_train)
#Predict Labels for x-test data
y_pred= classifier.predict(x_test) 
print('\nPredicted values:',y_pred)
     
#Confusion matrix with tested data
confMat = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix\n",confMat)

total_value = sum(sum(confMat))
#Accuracy TN+TP / P+N
accuracy=(confMat[0,0]+confMat[1,1])/total_value
print ('\nAccuracy : ', accuracy)

#Sensitivity TP/(TP+FN)
sensitivity = confMat[1,1]/(confMat[1,0]+confMat[1,1])
print('Sensitivity : ', sensitivity )

#Specificity TN/(TN+FP)
specificity = confMat[0,0]/(confMat[0,0]+confMat[0,1])
print('Specificity : ', specificity)

Dataset: 
 [[ 1  0]
 [ 2  0]
 [ 3  0]
 [ 6  0]
 [ 6  0]
 [ 7  0]
 [10  0]
 [11  0]] 
 Size:  8

Class labels Y: [0 0 1 1 1 0 0 0]

Training Data X: 
 [[6 0]
 [1 0]
 [7 0]
 [6 0]]

Training Data label Y: [1 0 0 1]

Predicted values: [1 1 1 1]

Confusion Matrix
 [[0 3]
 [0 1]]

Accuracy :  0.25
Sensitivity :  1.0
Specificity :  0.0
